"""add_movement_sessions

Revision ID: 2afa4caa191a
Revises: 475bbc2a4a21
Create Date: 2026-03-11 18:08:49.374034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2afa4caa191a'
down_revision: Union[str, Sequence[str], None] = '475bbc2a4a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movement_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('patient_id', sa.String(length=32), nullable=True),
    sa.Column('praxis_id', sa.String(length=32), nullable=True),
    sa.Column('session_type', sa.String(length=20), nullable=False),
    sa.Column('capture_mode', sa.String(length=20), nullable=False),
    sa.Column('camera_count', sa.Integer(), nullable=False),
    sa.Column('video_path', sa.String(length=512), nullable=True),
    sa.Column('keypoints_2d_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keypoints_3d_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('clinical_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('frame_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movement_sessions_patient_id'), 'movement_sessions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_movement_sessions_praxis_id'), 'movement_sessions', ['praxis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movement_sessions_praxis_id'), table_name='movement_sessions')
    op.drop_index(op.f('ix_movement_sessions_patient_id'), table_name='movement_sessions')
    op.drop_table('movement_sessions')
    # ### end Alembic commands ###
